[package]
name = "message"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.10.3"
borsh-derive = "0.10.3"
solana-program = "1.16.0"

[lib]
name = "message"
crate-type = ["cdylib", "lib"]
